### ISSUE TITLE
Modal doesn't close if you go back a page on your website.

### ISSUE THREAD

**Issue by YonatanToker** [themesberg/flowbite-angular#33]
https://github.com/themesberg/flowbite-angular/assets/116793943/661c92b8-9c0c-4dc1-ab55-07eee8e30873

If you go back your cannot click on anything you must refresh the page.

**Comment by TjasaZil** [comment]
I would like to be assigned to this issue, if it still needs to be done

**Comment by MGREMY** [comment]
@TjasaZil Hey
I tagged this issue in #46 
If you want to fix this issue, feel free to do :)

**Comment by TjasaZil** [comment]
@MGREMY No problem. I will fix the issue :)

**Comment by MGREMY** [comment]
Hello there
The PR where the fix is located has been merged into main.
However, the fix won't be out before some time because we are currently doing some refacto on the project.. Everybody will be notified when a new version will be released (containing this fix)
As a disclaimer, there will be breaking changes in the library so.. Be prepared to change many things ;)

**Comment by MGREMY** [comment]
Hey
Finally, the beta version is out (https://www.npmjs.com/package/flowbite-angular/v/1.0.0-beta.1). This issue will be fixed in the next version deployment (1.0.0)
