### ISSUE TITLE
Dropdown padding

### ISSUE THREAD

**Issue by bence444** [themesberg/flowbite-angular#59]
**Describe the bug**
Dropdown items have a huge gap on the left hand side (and on the y axis?).

**To Reproduce**
1. Go to https://flowbite-angular-git-reworkdocumentationfront-themesberg.vercel.app/docs/components/dropdown

**Expected behavior**
Zero padding on the left, just on the right of the dropdown. Padding y also looks a bit huge, compared to Flowbite and Flowbite React
- https://flowbite.com/docs/components/dropdowns/
- https://flowbite-react.com/docs/components/dropdown

**Screenshots**
![kép](https://github.com/user-attachments/assets/d3f6a064-d5b1-495c-b5ef-196ee9350063)
![kép](https://github.com/user-attachments/assets/a304b3c6-c4a6-4ac0-9b40-3f7485951d75)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Google Chrome, Firefox

**Additional context**
The `ul` element in the DropdownComponent has `py-1` class. By inspecting it you can see, the `ul` and `ol` tags have a `padding: revert` (i think it's default Tailwind setting), which causes the issue.

Note: i plain the make a PR for this, just opened an issue to make sure

**Comment by MGREMY** [comment]
I didn't saw that when I updated the css for the documentation project
The revert css value is used to prevent tailwindcss preflight css to hit it
Little hint, the css is in `apps\docs\src\styles.css`

This css style is here because otherwise, especially in the https://flowbite-angular-1bk729t0y-themesberg.vercel.app/docs/customize/override-base-style page, the list style is going to be removed

If you want to create a PR, don't forget to check on this page to see if lists are ok when generated with NgDoc

**Comment by MGREMY** [comment]
Fixed in #62
